bar:
  height: 28
  location: top
  background: 1a1b26ff # 1a1b26ff-TokyoNight 2e3440ff-Nord
  foreground: d2d9f8ff # d2d9f8ff-TokyoNight d8dee9ff-Nord
  font: JetBrainsMono NF:weight=bold:pixelsize=16
  spacing: 15

  left:
    - river:
        title:
          string:
            text: "{title}"
            left-margin: 10
            max: 105
        content:
          map:
            default: 
              string: {text: "{id}", margin: 12, foreground: 5e5f67ff} # 5e5f67ff-TokyoNight 575c66ff-Nord
            conditions:
              id > 9:
                empty: {}
              focused:
                string: {text: "{id}", margin: 12, deco: {background: {color: 5e5f67ff}}} # 5e5f67ff-TokyoNight 575c66ff-Nord
              occupied:
                string: {text: "{id}", margin: 12, foreground: d2d9f8ff} # d2d9f8ff-TokyoNight d8dee9ff-Nord

  # center:
  #   - clock:
  #       content:
  #         - string: {text: "", font: "JetBrainsMono NF:weight=bold:pixelsize=20", right-margin: 10}
  #         - string: {text: "{time}"}

  right:
    - backlight:
        name: intel_backlight
        content:
          - string: {text: "󰖨", font: "JetBrainsMono NF:weight=bold:pixelsize=22", right-margin: 10}
          - string: {text: "{percent}%"}
    - pulse:
        content:
          map:
            conditions:
              ~sink_muted:
                - ramp:
                    tag: sink_percent
                    font: "JetBrainsMono NF:weight=bold:pixelsize=25"
                    right-margin: 5
                    items:
                      - string: {text: "󰕿"}
                      - string: {text: "󰖀"}
                      - string: {text: "󰕾"}
                - string: {text: "{sink_percent}%"}
              sink_muted:
                - string: {text: "󰖁", font: "JetBrainsMono NF:weight=bold:pixelsize=25", right-margin: 7}
                - string: {text: "muted"}
    - battery:
        name: BAT0
        content:
          - ramp:
              tag: capacity
              font: "JetBrainsMono NF:weight=bold:pixelsize=19"
              right-margin: 17
              items:
                - string: {text: ""}
                - string: {text: ""}
                - string: {text: ""}
                - string: {text: ""}
                - string: {text: ""}
          - string: {text: "{capacity}%"}
    - mem:
        poll-interval: 2000
        content:
          - string: {text: "", font: "JetBrainsMono NF:weight=bold:pixelsize=20", right-margin: 10}
          - string: {text: "{used:mb}Mi"}
    - network:
        name: wlo1
        poll-interval: 5000
        content:
          map:
            default:
              - string: {text: "󰣼", font: "JetBrainsMono NF:weight=bold:pixelsize=20", right-margin: 7}
              - string: {text: "disconnected", right-margin: 10}
            conditions:
              state == "up":
                - string: {text: "󰣺", font: "JetBrainsMono NF:weight=bold:pixelsize=20", right-margin: 7}
                - string: {text: "{ssid}"}
    - clock:
        content:
          - string: {text: "", font: "JetBrainsMono NF:weight=bold:pixelsize=20", right-margin: 10}
          - string: {text: "{time}", right-margin: 10}

