#!/bin/sh

# This is the example configuration file for river.
#
# If you wish to edit this, you will probably want to copy it to
# $XDG_CONFIG_HOME/river/init or $HOME/.config/river/init first.
#
# See the river(1), riverctl(1), and filtile(1) man pages for complete
# documentation.

# Note: the "Super" modifier is also known as Logo, GUI, Windows, Mod4, etc.
# riverctl map normal Super P spawn "fuzzel -b 1a1b26ff -t d2d9f8ff -B 3 -r 0 -C d2d9f8ff -s 5e5f67ff -S d2d9f8ff -f JetBrainsMono\ Nerd\ Font:weight=medium:size=9 -M d2d9f8ff -m d2d9f8ff -w 50 -l 20 -i"
riverctl map normal Super P spawn "bemenu-run"
riverctl map normal Super+Shift Return spawn "foot"

# Super+Q to close the focused view
riverctl map normal Super Q close

# Super+Shift+E to exit river
riverctl map normal Super+Shift E exit
riverctl map normal Super+Shift Q spawn "systemctl poweroff"
riverctl map normal Super+Shift R spawn "systemctl reboot"

# Super+J and Super+K to focus the next/previous view in the layout stack
riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous

# Super+Shift+J and Super+Shift+K to swap the focused view with the next/previous
# view in the layout stack
riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous

# Super+Period and Super+Comma to focus the next/previous output
riverctl map normal Super Period focus-output next
riverctl map normal Super Comma focus-output previous

# Super+Shift+{Period,Comma} to send the focused view to the next/previous output
riverctl map normal Super+Shift Period send-to-output next
riverctl map normal Super+Shift Comma send-to-output previous

# Super+Return to bump the focused view to the top of the layout stack
riverctl map normal Super Return zoom

# Super+H and Super+L to decrease/increase the main ratio of filtile(1)
riverctl map normal Super H send-layout-cmd filtile "main-ratio -0.05"
riverctl map normal Super L send-layout-cmd filtile "main-ratio +0.05"

# Super+Shift+H and Super+Shift+L to increment/decrement the main count of filtile(1)
riverctl map normal Super+Shift H send-layout-cmd filtile "main-count +1"
riverctl map normal Super+Shift L send-layout-cmd filtile "main-count -1"

# riverctl hide-cursor when-typing enabled

# Super+Alt+{H,J,K,L} to move views
riverctl map normal Super+Alt H move left 100
riverctl map normal Super+Alt J move down 100
riverctl map normal Super+Alt K move up 100
riverctl map normal Super+Alt L move right 100

# Super+Alt+Control+{H,J,K,L} to snap views to screen edges
riverctl map normal Super+Alt+Control H snap left
riverctl map normal Super+Alt+Control J snap down
riverctl map normal Super+Alt+Control K snap up
riverctl map normal Super+Alt+Control L snap right

# Super+Alt+Shift+{H,J,K,L} to resize views
riverctl map normal Super+Alt+Shift H resize horizontal -100
riverctl map normal Super+Alt+Shift J resize vertical 100
riverctl map normal Super+Alt+Shift K resize vertical -100
riverctl map normal Super+Alt+Shift L resize horizontal 100

# Super + Left Mouse Button to move views
riverctl map-pointer normal Super BTN_LEFT move-view

# Super + Right Mouse Button to resize views
riverctl map-pointer normal Super BTN_RIGHT resize-view

# Super + Middle Mouse Button to toggle float
riverctl map-pointer normal Super BTN_MIDDLE toggle-float

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # Super+[1-9] to focus tag [0-8]
    riverctl map normal Super $i set-focused-tags $tags

    # Super+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal Super+Shift $i set-view-tags $tags

    # Super+Ctrl+[1-9] to toggle focus of tag [0-8]
    riverctl map normal Super+Control $i toggle-focused-tags $tags

    # Super+Shift+Ctrl+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

# Super+0 to focus all tags
# Super+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags

# riverctl map normal Super M toggle-fullscreen

# Super+Space to toggle float
riverctl map normal Super F toggle-float
riverctl map normal Super M send-layout-cmd filtile "monocle"
# riverctl map normal Super T send-layout-cmd filtile "main-location left"

# Super+{Up,Right,Down,Left} to change layout orientation
riverctl map normal Super Up    send-layout-cmd filtile "main-location top"
riverctl map normal Super Right send-layout-cmd filtile "main-location right"
riverctl map normal Super Down  send-layout-cmd filtile "main-location bottom"
riverctl map normal Super Left  send-layout-cmd filtile "main-location left"

# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor
riverctl declare-mode passthrough

# Super+F11 to enter passthrough mode
riverctl map normal Super F11 enter-mode passthrough

# Super+F11 to return to normal mode
riverctl map passthrough Super F11 enter-mode normal

# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
for mode in normal locked
do
    # Eject the optical drive (well if you still have one that is)
    riverctl map $mode None XF86Eject spawn 'eject -T'

    # Control pulse audio volume with pamixer (https://github.com/cdemoulins/pamixer)
    # riverctl map $mode None XF86AudioRaiseVolume  spawn 'pactl set-sink-volume @DEFAULT_SINK@ +5%'
    # riverctl map $mode None XF86AudioLowerVolume  spawn 'pactl set-sink-volume @DEFAULT_SINK@ -5%'
    # riverctl map $mode None XF86AudioMute         spawn 'pactl set-sink-mute @DEFAULT_SINK@ toggle'
    riverctl map $mode None XF86AudioRaiseVolume  spawn '$HOME/.config/river/volume.sh up'
    riverctl map $mode None XF86AudioLowerVolume  spawn '$HOME/.config/river/volume.sh down'
    riverctl map $mode None XF86AudioMute         spawn '$HOME/.config/river/volume.sh mute'

    # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
    riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPlay  spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPrev  spawn 'playerctl previous'
    riverctl map $mode None XF86AudioNext  spawn 'playerctl next'

    # Control screen backlight brightness
    # riverctl map $mode None XF86MonBrightnessUp   spawn 'brightnessctl s +5%'
    # riverctl map $mode None XF86MonBrightnessDown spawn 'brightnessctl s 5%-'
    riverctl map $mode None XF86MonBrightnessUp   spawn '$HOME/.config/river/brightness.sh up'
    riverctl map $mode None XF86MonBrightnessDown spawn '$HOME/.config/river/brightness.sh down'
    riverctl map $mode None Print spawn 'grim -g "$(slurp)" - | wl-copy'
    riverctl map $mode Shift Print spawn 'grim -g "$(slurp)" - > ~/pictures/$(date +%y%m%d%H%M%S).png'
done

# Set background and border color
riverctl border-color-focused 0xd2d9f8 # 0xd2d9f8-TokyoNight 0xd8dee9-Nord
riverctl border-color-unfocused 0x5e5f67 # 0x5e5f67-TokyoNight 575c66ff-Nord
riverctl border-width 3
riverctl focus-follows-cursor always

# Set keyboard repeat rate
riverctl set-repeat 25 300

# Make certain views start floating
riverctl float-filter-add app-id float
riverctl float-filter-add title "Firefox — Sharing Indicator"

# Set app-ids and titles of views which should use client side decorations

# Layout
riverctl default-layout filtile
# rivercarro -inner-gaps 5 -outer-gaps 5 -no-smart-gaps &
filtile -view-padding 0 -outer-padding 0 &

# Rules
# riverctl rule-add -app-id "*" ssd
riverctl rule-add -app-id "firefox" ssd
riverctl rule-add -app-id "evince" ssd
riverctl rule-add -app-id "imv" ssd
riverctl rule-add -app-id "remote-viewer" ssd
riverctl rule-add -app-id "thunderbird" ssd
riverctl rule-add -app-id "libreoffice-startcenter" ssd
riverctl rule-add -app-id "blueberry.py" ssd
riverctl rule-add -app-id "nwg-look" ssd
riverctl rule-add -app-id "telegram" ssd

# Devices
riverctl keyboard-layout -options grp:win_space_toggle us,ru
riverctl input pointer-1267-12541-ELAN0712:00_04F3:30FD_Touchpad pointer-accel 0.3
riverctl input pointer-1267-12541-ELAN0712:00_04F3:30FD_Touchpad tap enabled
riverctl input pointer-1267-12541-ELAN0712:00_04F3:30FD_Touchpad natural-scroll enabled

# Autostart
# riverctl spawn "/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1"
riverctl spawn "/usr/lib/polkit-kde-authentication-agent-1"
riverctl spawn "swaybg -m fill -i ~/pictures/groot-dark.png"
# riverctl spawn "waybar -s $HOME/.config/river/waybar/style.css -c $HOME/.config/river/waybar/config.jsonc"
riverctl spawn "yambar -c $HOME/.config/river/yambar/config.yml &"

export XDG_CURRENT_DESKTOP=river
export XDG_SESSION_DESKTOP=river
dbus-update-activation-environment --all
